### ISSUE TITLE
Emails are being sent with bb tags and not formatted

### ISSUE THREAD

**Issue by nquamdbridge** [mantisbt-plugins/BBCodePlus#10]
I'm not sure what "Process email" does but I assumed it would convert bbcode into html for emails. I am having a problem where the emails sent out show the bbcode and it's a mess. Is this a bug? Is it maybe my version? I have the last 1.2 version of your plugin.

Mantis Version: 1.2.17
Schema Version: 183

**Comment by bkraul** [comment]
@nquamdbridge: Mantisbt does not support HTML emails by default. The functionality in BBCodePlus is there, for when HTML emails become a user-configurable option, which I think will be coming soon onto Mantis 1.3. It is also there for installations where the user manually modifies the mantis installation to allow HTML emails (core/email_api.php around line 1113). However, you bring up an important issue. I should be stripping out all BBCode tags when "Process Email" is disabled. I will check that and submit a new version if necessary. It is necessary to point out, however, that some features, such as code syntax highlighting are unavailable in emails due to the javascript needed to perform.

**Comment by nquamdbridge** [comment]
Yeah if you could just strip out those code tags somehow, that would help a lot. Emails can look pretty messy if you use a lot of those tags.

**Comment by bkraul** [comment]
@nquamdbridge I have released version 1.0.9 adding support for stripping all bbcode tags when the setting to process text, email or rss is set to **No**. This will make the text showing on your emails readable and free of html objects. Please let me know if this works for you, so I can close the issue.

**Comment by bkraul** [comment]
My apologies. There was an issue with the released version that was adding unwanted <br> objects to the content. Please download latest master 1.0.10.

**Comment by bkraul** [comment]
@nquamdbridge, any news on this solving your problem?

**Comment by bkraul** [comment]
Closed due to no response. Will reopen in the event of issues with implemented solution.

**Comment by PhSoundsLikeF** [comment]
This post helped me out!
Changed the 'process_email' setting and now our email notifications are no longer garbled with markup
Thanks!
