### ISSUE TITLE
clipboard.min.js not found

### ISSUE THREAD

**Issue by abc874** [mantisbt-plugins/BBCodePlus#104]
Version 2.1.18

`/plugin_file.php?file=BBCodePlus/prism/clipboard.min.js` in prism.js throws

>"GET /plugin_file.php?file=BBCodePlus/prism/clipboard.min.js HTTP/1.1" 404 196
in Apache access.log

and
>script 'xxxxx/mantisroot/plugin_file.php' not found or unable to stat
in Apache error.log

**Comment by bkraul** [comment]
Seems this is pointing at your mantis installation. Does `plugin_file.php` exist in your mantis root, and is your apache installation calling PHP scripts properly?

**Comment by abc874** [comment]
Just changed

`n.src="/plugin_file.php?file=BBCodePlus/prism/clipboard.min.js"`

to

`n.src="plugin_file.php?file=BBCodePlus/prism/clipboard.min.js"`

and error is gone. Code 200 in Apache-Log.

**Comment by bkraul** [comment]
Seems your mantis root setting might be mis-configured. There should be no need to remove the `/` in the source code, if the setting correctly specifies where to find the mantis root, as the proper path is automatically added.

That said, could you tell me which source file you changed in order to make it work so I can verify?

**Comment by abc874** [comment]
All other plugins and calls to plugin_file.php are working.
In your CSS is also no slash.

`background-image: url("plugin_file.php?file=BBCodePlus/markitup/sets/mantis/images/bold.png");`

clipboard.min.js is only in prism.js used.
There was the slash.
