### ISSUE TITLE
"indentation  increase/decrease" and the table creation

### ISSUE THREAD

**Issue by ideefox** [mantisbt-plugins/BBCodePlus#23]
Hi Belman, Hi Kirill,
Your editor is a great help for formatting the text input. May I ask you if the editor could be added  by the functions of the "indentation  increase/decrease" and the table creation?
The texts will looked much better.
Regards from Cologne

**Comment by bkraul** [comment]
@ideefox sorry to take so long to get back to you on this. Things have been really busy. I have begun reworking the plugin to allow better reliability and features. This feature request is interesting. Would you mind providing a little bit more detail, and perhaps a small example of how you'd see this working?

The issue is that there is no current "standard" BBCode that addresses indentation. Therefore we'd have to come up with our own. Also, what do you mean by "table creation"?

Regards from Memphis.

**Comment by bkraul** [comment]
Closed due to lack of feedback.
