### ISSUE TITLE
markitup icons not working

### ISSUE THREAD

**Issue by jsandner** [mantisbt-plugins/BBCodePlus#31]
Mantis 2.18.0
BBCodePlus 2.0.15

The markitup editor doesnt show the Icons (Bold, italic, etc.) in the Browser.
These Icons are fetched like http://myhost/plugin_file.php?file=BBCodePlus/markitup/sets/mantis/images/justify.png
But when fetched this way, the icons are broken. "justify.png" e.g. is 214 Byte big instead of 209 Bytes.
5 leading 0x0a are inserted in the begining
is:
00000000: 0a0a 0a0a 0a89 504e 470d 0a1a 0a00 0000  ......PNG.......
should be:
0000000: 8950 4e47 0d0a 1a0a 0000 000d 4948 4452  .PNG........IHDR

**Comment by bkraul** [comment]
Check the current content security policy for your mantis installation. The default one (none specified in config) from mantis should work. Have you made changes to tighten it, by any chance?

**Comment by jsandner** [comment]
No, didn't tighten security in any way. The images are downloaded, but cannot be shown, because they are corrupt.
When I open the URL http://myhost/plugin_file.php?file=BBCodePlus/markitup/sets/mantis/images/justify.png in Firefox, it says, it cannot show the image because it contains errors.
The image on the server is OK, but when downloaded with "plugin_file.php", 5 "Newline" (\n) are inserted  in the beginning.

**Comment by bkraul** [comment]
Then that would mean there is somewhere in your installation that is inserting the new line. Try disabling other plugins and re-enable them one by one while checking that URL. Also make sure your config file has no new line characters at the end. This is likely happening due to the fact that several scripts are loaded/included before the plugin_file.php runs, and one of those has extra new line characters. This includes, config, core, language, and others.

**Comment by bkraul** [comment]
Check the following user files:
* ```custom_constants_inc.php``` (you  may not have this one if not using custom constants).
* ```config_inc.php```

**Comment by jsandner** [comment]
YESSSS.
Amazing .... there were some empty lines at the end of 2 config files.
Great solution, Thank you.
