### ISSUE TITLE
Regression: Unable to recognize image URL scheme of phpbb (forum software) 

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/BBCodePlus#86]
Reference:  
* https://mantisbt.org/bugs/view.php?id=26146  
* https://freecadweb.org/tracker/view.php?id=4023

**Comment by bkraul** [comment]
@luzpaz,

Please clarify what the issue is and what it is exactly affecting (i.e. web or email notifications), preferably with screenshots, also including the version of BBCodePlus (and MantisBT) you are using. Below is using plugin version 2.1.11 ([latest](https://github.com/mantisbt-plugins/BBCodePlus/releases/tag/v2.1.11)) on MantisBT 2.19.1:

Plugin List:
![image](https://user-images.githubusercontent.com/14616851/64978834-04d31f00-d87c-11e9-81cd-62f07f16cf39.png)

Code:
![image](https://user-images.githubusercontent.com/14616851/64978723-c8072800-d87b-11e9-8bbb-59bf124fe27f.png)

Rendering:
![image](https://user-images.githubusercontent.com/14616851/64978758-dfdeac00-d87b-11e9-8e44-e95fe6429c36.png)

The [screenshot ](https://freecadweb.org/tracker/view.php?id=4023) posted in the forum that I assume is the one where you are experiencing the issue does not show a screenshot, but a CAD section:

![image](https://user-images.githubusercontent.com/14616851/64979658-c179b000-d87d-11e9-97eb-88329bc7b5b6.png)

**Comment by luzpaz** [comment]
Yikes, I forgot that we didn't upgrade. Still using 2.0.15. Will test and report back soon.

**Comment by luzpaz** [comment]
Looks like upgrading fixed it! Thanks...
BTW...we're noticing a problem that may be a direct result of updating to latest bbcodeplus, adding a hashtag in front of a number to link to other mantis tickets isn't working anymore...can you confirm ?

**Comment by bkraul** [comment]
You have to have Mantis Core Formatting enabled (specifically the feature to create bug, note, and other links) . BBCode plus no longer emulates this on its own. Please try that and let me know.

**Comment by luzpaz** [comment]
Thanks!
