### ISSUE TITLE
Email confirmation link broken

### ISSUE THREAD

**Issue by intervisionlord** [mantisbt-plugins/BBCodePlus#89]
Using this plugin email link became broken

`<a target="_blank" href="https://XXXXX/verify.php?id=10`**`&amp;`**`confirm_hash=XXXXX">https://XXXXX/verify.php?id=10&confirm_hash=XXXXX</a>`

https://www.mantisbt.org/bugs/view.php?id=26338

**Comment by quazardous** [comment]
Same here

```
Une NOTE a été ajoutée à cette anomalie.

----------------------------------------------------------------------
 (0004705) XXX (client) - 2020-01-14 11:03
 https://mantis.xxx.net/view.php?id=554#c4705
```

became

```
Une NOTE a été ajoutée à cette anomalie.

----------------------------------------------------------------------
 (0004707) XXX (client) - 2020-01-14 11:16
 <a target="_blank"
href="https://mantis.xxx.net/view.php?id=554#c4707">https://mantis.xxx.net/view.php?id=554#c4707</a>
```

**Comment by bkraul** [comment]
I know it has been a while since this issue was first posted. I am trying to address it. I can replicate the issue. However, it only happens when you have the "Process Email" option turned on. It works fine with it off. So my question is. Is there any reason why you are processing email with the plugin? Mantis does not support HTML emails, so any use of BBCode in the emails is pointless.
