### ISSUE TITLE
BBCodePlus 1.0.8 and Explorer 11

### ISSUE THREAD

**Issue by ConnerMcLoud** [mantisbt-plugins/BBCodePlus#9]
Hello,

i have an Issue with BBCode using in Mantis BugTracker
I am using Mantis BT-> 1.2.15 and BBCode+ 1.0.8 as Plugin. 

Everything is orking without any Issues in Firefox. If i try to open Mantis BT in Internet Explorer 11 the Menu from BBCode is shown as you can see in the Pictures below. 

Is it possible to fix this?

FireFox: 
http://www.syntax-networks.de/mantis/firefox.jpg

Internet Explorer 11
http://www.syntax-networks.de/mantis/explorer.jpg

Thx

**Comment by bkraul** [comment]
@ConnerMcLoud thank you for your report. Would you please provide a little more information for me:

-List of any other mantis plugins you currently have active (with their versions).
-Operating system.
-Any javascript/css error data from Internet Explorer Developer tools (F12).

**Comment by ConnerMcLoud** [comment]
Hello,
here are some more Details:

Operating System Server:
Microsoft Windows Server 2008 R2 (64Bit)  / Installed XAMPP Version 1.8.3

Guest Operating System: 
Windows 7 32 Bit Internet Explorer 11 

All installed Plugins:
Admin Set Password 0.1.2
BBCode+ 1.0.8
Import/Export issues 1.0
jQuery Library 1.11.1
jQuery UI Library 1.11.4
Lightbox Integration 1.0
Mantis Graphs 1.0
MantisBT Core 1.2.15
MantisBT Formatting 1.0a

Data from Internet Explorer DevTools: 
http://www.syntax-networks.de/mantis/f12.jpg
There are no other Messages ...

Thanks

**Comment by bkraul** [comment]
@ConnerMcLoud, I installed all the plugins you currently use, with the version of mantis you are using (1.2.15). Using IE11 on Windows 7-32bit, I cannot replicate the behavior you report.

From the errors i see in the DevTools, the ones that would seem to cause the behavior are the ones relating to mime types, which would hint to a file encoding problem. I would re-download the BBCode plugin and reinstall.

If this is not working you might want to look at what your php environment is using for the following settings:

[default_mimetype](http://php.net/manual/en/ini.core.php#ini.default-mimetype)
[default_charset](http://php.net/manual/en/ini.core.php#ini.default-charset)

These are the only errors I am getting, which seem to be from the mantis installation itself, and should be of no consequence. Let me know if this helps.

![dev](https://cloud.githubusercontent.com/assets/14616851/12266844/e3de89ae-b90a-11e5-9440-3b8cb28680c0.png)

**Comment by ConnerMcLoud** [comment]
Thanks. But this is not working. I asked the same question here: https://www.mantisbt.org/forums/viewtopic.php?f=9&t=23545 they are able to reproduce but asked me to post the Issue here. They also thought that it is because of the IE11 Security IE11 don't want to load the CSS. 

If i enable Private Browsing inside IE11 it works...

But OK, i need to find another solution. 

Thanks for your Help

EDIT: Not Private Browsing .... Compatibility View Settings

**Comment by bkraul** [comment]
@ConnerMcLoud I went to the mantis forum you linked. From Atrol's response (hoping Google translate works properly), I see that he says he knows what the problem is, but I could not see that he was able to reproduce. @atrol (I am assuming you are the same one from the forums), do you have any information as to how I can reproduce these security issues? I have not changed the security settings for IE11.

**Comment by bkraul** [comment]
I have been researching this, and the environment you describe suggests an intranet configuration. The SEC7113: css was ignored due to mime type mismatch appears to be a pretty common error, with some weird situations happening.

In this particular case, a solution I found said that in intranet servers that have an underscore (accessed as http://my_server), the error would prevent CSS content from being loaded. It suggested renaming or aliasing the server name to something without the underscore, such as http://myserver, or http://my-server. ( [link here](https://social.technet.microsoft.com/Forums/en-US/e0e8bc22-827a-4596-8d5e-4719a5079fee/solvedforms-not-rendering-in-new-environment-with-ie?forum=sharepointadmin) )

Does this seem to match your situation?

Here is [another link](http://tridion.stackexchange.com/questions/2313/blocked-css-files-for-session-preview-only-in-internet-explorer) to another potential solution, dealing with file types.

**Comment by atrol** [comment]
I had been able to reproduce the issue.
My testing environment was latest Mantis2Go (which means MantisBT 1.2.19, Apache, PHP 5.3.2, accessed as http://127.0.0.1:4001) on Windows 10.
Additional plugins just jQuery Library and BBCode+.

**Comment by bkraul** [comment]
I am stumped. I set up a fresh local environment with:
MantisBT 1.2.20 (master-1.2.x)
Apache + PHP 5.6.16 + MySQL 5.6.20 (UwAmp 3.0.2 portable)
With only plugins: Core, jQuery Library and BBCode+
Accessed as http://127.0.0.1/mantis12 on Windows 10.

No errors.

I guess I will try 1.2.19 with PHP 5.3.2.

![image 2](https://cloud.githubusercontent.com/assets/14616851/12308421/d0c85588-ba0a-11e5-9da1-b5803d9533cc.png)

**UPDATE**: Same results with PHP 5.3.2.

**Comment by bkraul** [comment]
Closed due to inability to reproduce behavior. Region-dependent encoding issues suspected.

**Comment by RamshackleJoe** [comment]
I had the same issue, it turned out to be a missing PHP extension add this to your PHP.ini file:
`extension=php_fileinfo.dll`
